// Package context provides constants for tracking context variables.
package context

// Context constants.
const (
	Account              = "account"
	AccountEmail         = "accountEmail"
	AccountID            = "accountID"
	AccountJWT           = "accountJWT"
	AccountJWTExpiration = "accountJWTExpiration"
	AccountXSRFState     = "accountXSRFState"
	AuthProviderID       = "authProviderID"
	BLOBID               = "blobID"
	BLOBProviderID       = "blobProviderID"
	ClientDate           = "clientDate"
	ClientID             = "clientID"
	Collection           = "collection"
	Database             = "database"
	DataProviderID       = "dataProviderID"
	Exchange             = "exchange"
	File                 = "file"
	Hostname             = "hostname"
	IndexID              = "indexID"
	Line                 = "line"
	NodeID               = "nodeID"
	NodeType             = "nodeType"
	NodeURI              = "nodeURI"
	Nonce                = "nonce"
	ObjectIDs            = "objectIDs"
	Referer              = "referer"
	RequestDuration      = "requestDuration"
	RequestID            = "requestID"
	RequestIP            = "requestIP"
	RequestMethod        = "requestMethod"
	RequestStart         = "requestStart"
	RequestURL           = "requestURL"
	ResponseCode         = "responseCode"
	ResponseLength       = "responseLength"
	SearchEngineID       = "searchEngineID"
	SecretProviderID     = "secretProviderID"
	SegmentDuration      = "segmentDuration"
	SegmentStart         = "segmentStart"
	TelemetryID          = "telemetryID"
	WebhookID            = "webhookID"
	WebhookEndpointURL   = "webhookEndpointURL"
	WebhookEventID       = "webhookEventID"
	WebhookEventType     = "webhookEventType"
	WorkerID             = "workerID"
)
